hash-ring-test:
	mvn -Dexec.classpathScope=test -Dexec.mainClass=de.hstr.bigdata.conshash.HashRingTest exec:java

distribution-test:
	mvn -Dexec.classpathScope=test -Dexec.mainClass=de.hstr.bigdata.conshash.DistributionTest exec:java

virtual-distribution-test:
	mvn -Dexec.classpathScope=test -Dexec.mainClass=de.hstr.bigdata.conshash.VirtualDistributionTest exec:java
